spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

project:
  poster: poster/

base:
  url: "http://localhost:8080"
